### ISSUE TITLE
Haven't gotten purchased extension

### ISSUE THREAD

**Issue by shellycole** [ReduxFramework/redux-extensions#140]
Hi there :)

I purchased the Repeater extension yesterday (about 24 hours ago).  I haven't received anything yet - and yes, I have checked my spam folders.

Is there some other step I'm not aware of to get the extension?

Thanks!

**Comment by dovy** [comment]
Sorry that's not clear. Go to http://ReduxFramework.com/account and you will be able to download it there. Best of luck!

**Comment by shellycole** [comment]
It's not there.  When I bought it, it didn't have me create an account (but I did go back to create one - but it isn't there for download.)

**Comment by dovy** [comment]
Oh... Send me your username. I'm out for the day, but I'll set your account up right first thing tomorrow. 

I thought I made it force account creation. :(

**Comment by shellycole** [comment]
Gotcha.  No problem (I'm not in a *huge* hurry).  the account name for Redux is "shellycodes".  The transaction id (for paypal) is #67209778TC844015P

And yeah, I thought maybe something happened - when I finished making the payment, it just stayed on the PayPal page, it never redirected. I figured I'd get an email from you all so I could finish whatever it is I needed to do, but it never came (Paypal's receipt did, though).  I thought I'd give it 24 hours (and double-check spam) before I put in a request, in case some connection along the line was slow.  But it never did, so here I am!

Thanks for the help :)

**Comment by shellycole** [comment]
Is there anything else I need to send you to get this extension?  I know I said I wasn't in any hurry, but it'd be nice to have it to work on what I'm doing this weekend.

Thanks!

**Comment by dovy** [comment]
Sorry, I'll have it done first thing in the morning.

**Comment by dovy** [comment]
Shelly:
I can't find record of it anywhere! Are you sure the payment went through?

**Comment by dovy** [comment]
Found it. It's because you didn't use the same email and you weren't signed in. It should be resolved now.  :)

**Comment by shellycole** [comment]
Thanks!  Sorry, I should have passed my paypal email address - I have an email I use for all my online purchases, and it's not the same as the email I use for work stuff.

It's showing up in my account now, but the download still isn't there - says the payment is still pending, and I can only download the invoice - and when I click on the invoice I get a message that says "the invoice you requested is not found."

**Comment by dovy** [comment]
Shelly:
Fixed it. So sorry. Thank you for being so patient.

**Comment by shellycole** [comment]
Thank you so much! I appreciate the help :) (And I know how busy you guys are)

**Comment by dovy** [comment]
Thank you for the support. ;)
